USE ROLE APPS_DBA;
CREATE DATABASE IF NOT EXISTS FDB_DEVOPS;
CREATE SCHEMA IF NOT EXISTS FDB_DEVOPS.SCH_DEVOPS;
GRANT OWNERSHIP ON SCHEMA FDB_DEVOPS.SCH_DEVOPS TO ROLE MNG_DMN_ADMIN;
GRANT ALL ON SCHEMA FDB_DEVOPS.SCH_DEVOPS TO ROLE MNG_DMN_ADMIN;
 
create or replace TRANSIENT TABLE FDB_DEVOPS.SCH_DEVOPS.METRICS_DEVOPS (
	MODEL_NAME VARCHAR(16777216),
	FILE_NAME VARCHAR(16777216),
	MEAN_ABSOLUTE_ERROR_SCORE FLOAT,
	MEAN_SQUARED_ERROR_SCORE FLOAT,
	R2_SCORE FLOAT,
	DATE VARCHAR(16777216)
);
 
create or replace stream FDB_DEVOPS.SCH_DEVOPS.STREAM_METRICS_DEVOPS on table METRICS_DEVOPS;
 
create or replace task FDB_DEVOPS.SCH_DEVOPS.TASK_METRICS_DEVOPS
	warehouse=VWH_LIGHT_ETL_MNG
	schedule='60 MINUTE'
	when system$stream_has_data('STREAM_METRICS_DEVOPS')
	as call FDB_DEVOPS.SCH_DEVOPS.sp_Load_Metrics_Devops();